"""Public typed runtime contracts for the future proxy."""

from .common import (
    BoundedJsonPatch,
    InternalStrictModel,
    OpenAIMessageModel,
    OpenAIRequestModel,
    validate_bounded_json_patch,
)
from .ingestion import (
    ParsedIngestedContext,
    RecentExchange,
    ResolvedTurnContext,
    SamplingParameters,
)
from .mechanics import (
    ConditionAddUpdate,
    ConditionName,
    ConditionRemoveUpdate,
    DeterministicMechanicalUpdate,
    HpDamageUpdate,
    HpHealingUpdate,
    HpSetUpdate,
    ResourceDeltaUpdate,
    ResourceName,
)
from .openai import (
    AssistantResponseMessage,
    ChatCompletionChunk,
    ChatCompletionRequest,
    ChatCompletionRequestBase,
    ChatCompletionResponse,
    CompletionChoice,
    NonStreamingChatCompletionRequest,
    StreamChoice,
    StreamDelta,
    StreamingChatCompletionRequest,
    StringChatMessage,
    TokenUsage,
)
from .rules import DiceRollRequest, RulesAdjudicationResult
from .storyteller import (
    AppliedEmotionalAxisChange,
    ConversationalFactCandidate,
    EmotionalAxisDeltas,
    EmotionalShift,
    MajorEvent,
    PlotStateUpdate,
    SceneGraphPatch,
    SceneObjectPatch,
    StorytellerOutput,
    StorytellerStateUpdate,
    WorldStatePatch,
)

__all__ = [
    "AppliedEmotionalAxisChange",
    "AssistantResponseMessage",
    "BoundedJsonPatch",
    "ChatCompletionChunk",
    "ChatCompletionRequest",
    "ChatCompletionRequestBase",
    "ChatCompletionResponse",
    "CompletionChoice",
    "ConditionAddUpdate",
    "ConditionName",
    "ConditionRemoveUpdate",
    "ConversationalFactCandidate",
    "DeterministicMechanicalUpdate",
    "DiceRollRequest",
    "EmotionalAxisDeltas",
    "EmotionalShift",
    "HpDamageUpdate",
    "HpHealingUpdate",
    "HpSetUpdate",
    "InternalStrictModel",
    "MajorEvent",
    "NonStreamingChatCompletionRequest",
    "OpenAIMessageModel",
    "OpenAIRequestModel",
    "ParsedIngestedContext",
    "PlotStateUpdate",
    "RecentExchange",
    "ResolvedTurnContext",
    "ResourceDeltaUpdate",
    "ResourceName",
    "RulesAdjudicationResult",
    "SamplingParameters",
    "SceneGraphPatch",
    "SceneObjectPatch",
    "StreamChoice",
    "StreamDelta",
    "StreamingChatCompletionRequest",
    "StringChatMessage",
    "StorytellerOutput",
    "StorytellerStateUpdate",
    "TokenUsage",
    "WorldStatePatch",
    "validate_bounded_json_patch",
]
